apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MongoDb__ConnectionString: "mongodb+srv://martinsandung:IDjcjDU7aeePGhEX@cluster1.chdrb4f.mongodb.net/?retryWrites=true&w=majority"
  MongoDb__DatabaseName: "Person"
